### ISSUE TITLE
token not valid to retrieve profile picture

### ISSUE THREAD

**Issue by ThomasSchoenbeck** [fairmutex/ngx-adal-8#3]
Hello,

using this package is really straightforward and I like it quite a lot. What i can't get to work is retrieving the users profile picture. The access token which is given upon login, is not valid to retrieve any content from the https://graph.microsoft.com/ api.

for example i should be able to get the picture from https://graph.microsoft.com/beta/me/photo/$value but I get only 401 instead.

**Comment by fairmutex** [comment]
Hi, Sorry for the late reply. You can solve the 401 issue with regards to Graph API access you need to set the endpoint 

```
      endpoints: {
         'https://graph.microsoft.com': 'https://graph.microsoft.com'
      }, 
```

However you will encounter a 404 on https://graph.microsoft.com/v1.0/me/photo/$value and that is not because of the library. You can see this happening even here https://developer.microsoft.com/en-us/graph/graph-explorer to be able to access the image you need to give permission on azure side
