### ISSUE TITLE
Unable to set a list of anonymousEndpoints

### ISSUE THREAD

**Issue by jperez-turner** [fairmutex/ngx-adal-8#5]
I'm using the library and I need to ignore a couple of endpoints from being set with the authentication token. I sent the property `anonymousEndpoints` to the adal config and once you call `this.context.getResourceForEndpoint(url);` in `ngx-adal-8.js` we got a `null` as an answer. But, right after that, there's a condition to return the clientId as the resource value. So, I'm currently unable to ignore some endpoints, is there otherway of doing that, or can I send a PR deleting that condition?

Regards,

**Comment by fairmutex** [comment]
The idea is that you don't need to set the anonymousEndpoints that need to be ignored as the [interceptor](https://github.com/fairmutex/ngx-adal-8/blob/master/projects/ngx-adal-8/src/lib/ngx-adal.interceptor.ts) is taking care checking if the URL is a relevant resource in the case that it isn't, it will return immediately without authentication logic.

**Comment by juancapm09** [comment]
We have an API, which has endpoints that requires Auth token, others not. I dont understand how to define relevancy for endpoints, as we're getting an auth token attached to all the requests. Because in the [adal-service](https://github.com/fairmutex/ngx-adal-8/blob/636e3a706ca1731cc6091093b066675ae3e0579f/projects/ngx-adal-8/src/lib/ngx-adal.service.ts#L41) if the resource has not value the `clientId` is returned instead. So, the [interceptor ](https://github.com/fairmutex/ngx-adal-8/blob/master/projects/ngx-adal-8/src/lib/ngx-adal.interceptor.ts) is always setting the auth token.

**Comment by fairmutex** [comment]
Install version 0.0.5, you will be able to set anonymousEndpoints array. Let me know if you encounter further problems.

**Comment by juancapm09** [comment]
thanks!
